{
 "title": "Метрики менторов",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Количество менторов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('minute', created_at) AS created_at_trunc, COUNT(*) AS count\nFROM mentor\nGROUP BY created_at_trunc\nORDER BY created_at_trunc;"
    }
   ]
  },
  {
   "title": "Соотношение принятых заявок к не рассмотренным",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*), type\nFROM mentoring_request \nGROUP BY type;"
    }
   ]
  },
  {
   "title": "Общее количество",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    (SELECT COUNT(*) FROM mentor) AS mentor_count,\n    (SELECT COUNT(*) FROM mentoring_request) AS request_count;"
    }
   ]
  },
  {
   "title": "Соотношение студентов на менторов",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    (SELECT COUNT(*) FROM student) AS student_count,\n    (SELECT COUNT(*) FROM mentor) AS mentor_count;\n"
    }
   ]
  }
 ]
}