apiVersion: 1

datasources:
    - name: PostgreSQL
      type: postgres
      access: proxy
      url: db:5432
      database: postgres
      user: postgres
      secureJsonData:
          password: "postggpass"
      jsonData:
          sslmode: "disable"
          maxOpenConns: 10
          maxIdleConns: 5
          connMaxLifetime: 14400
      version: 1
      editable: true
