{
 "title": "Метрики cтудентов",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Количество студентов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('minute', created_at) AS created_at_trunc, COUNT(*) AS count\nFROM student\nGROUP BY created_at_trunc\nORDER BY created_at_trunc;"
    }
   ]
  },
  {
   "title": "Общее количество",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    (SELECT COUNT(*) FROM student) AS student_count,\n    (SELECT COUNT(*) FROM mentoring_request) AS request_count,\n    (SELECT COUNT(*) FROM swiped_mentor) as swipes_count;"
    }
   ]
  },
  {
   "title": "Соотношение студентов на менторов",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    (SELECT COUNT(*) FROM student) AS student_count,\n    (SELECT COUNT(*) FROM mentor) AS mentor_count;\n"
    }
   ]
  }
 ]
}