"""['unique']

Revision ID: 04b0501a963c
Revises: 388a41de3e61
Create Date: 2025-03-01 15:43:00.446089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b0501a963c'
down_revision = '388a41de3e61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'student', ['full_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='unique')  # type:ignore
    # ### end Alembic commands ###