"""['avatar url']

Revision ID: 29fa2391d93a
Revises: 95d39348bb6f
Create Date: 2025-03-01 09:57:06.454711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29fa2391d93a'
down_revision = '95d39348bb6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'avatar_url')
    # ### end Alembic commands ###