"""['add mentor age']

Revision ID: 388a41de3e61
Revises: 8ca264562d2b
Create Date: 2025-03-01 15:12:38.972937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388a41de3e61'
down_revision = '8ca264562d2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentor', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentor', 'age')
    # ### end Alembic commands ###