"""['fix review']

Revision ID: 4454d16b84e0
Revises: e122430f6a45
Create Date: 2025-03-02 21:32:10.541225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4454d16b84e0'
down_revision = 'e122430f6a45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentor_review', sa.Column('review_id', sa.Uuid(), nullable=False))
    op.create_unique_constraint(None, 'mentor_review', ['student_id', 'mentor_id'])
    op.alter_column('student', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'mentor_review', type_='unique')
    op.drop_column('mentor_review', 'review_id')
    # ### end Alembic commands ###