"""['student description']

Revision ID: 6527e36c6bda
Revises: 77d24c94b7e7
Create Date: 2025-03-02 11:39:24.232662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6527e36c6bda'
down_revision = '77d24c94b7e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'description')
    # ### end Alembic commands ###