"""['remove mentor age']

Revision ID: 77d24c94b7e7
Revises: bd7ecb8aad62
Create Date: 2025-03-02 09:39:31.453002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d24c94b7e7'
down_revision = 'bd7ecb8aad62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentor', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentor', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###