"""['swipe']

Revision ID: 80444d37ab09
Revises: 85ea63199333
Create Date: 2025-03-01 19:03:28.553311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80444d37ab09'
down_revision = '85ea63199333'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentoring_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mentor_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('REVIEW', 'ACCEPTED', 'REJECTED', name='mentoringrequesttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swiped_mentor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mentor_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('LIKE', 'DISLIKE', 'FAVORITES', name='swipedmentortype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('selected_mentor')
    op.create_unique_constraint(None, 'student', ['full_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='unique')  # type: ignore
    op.create_table('selected_mentor',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('mentor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('LIKE', 'DISLIKE', 'FAVORITES', name='selectedmentortype'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.id'], name='selected_mentor_mentor_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='selected_mentor_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='selected_mentor_pkey')
    )
    op.drop_table('swiped_mentor')
    op.drop_table('mentoring_request')
    # ### end Alembic commands ###