"""['add entites']

Revision ID: 85ea63199333
Revises: 04b0501a963c
Create Date: 2025-03-01 18:46:24.480239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ea63199333'
down_revision = '04b0501a963c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_full_name_key', 'student', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('student_full_name_key', 'student', ['full_name'])
    # ### end Alembic commands ###