"""['unique request']

Revision ID: a8ec8cb276d5
Revises: 4454d16b84e0
Create Date: 2025-03-03 06:32:23.543376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ec8cb276d5'
down_revision = '4454d16b84e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'mentoring_request', ['student_id', 'mentor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mentoring_request', type_='unique')
    # ### end Alembic commands ###