"""['mentor contact']

Revision ID: bd7ecb8aad62
Revises: 80444d37ab09
Create Date: 2025-03-02 08:15:37.413657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd7ecb8aad62'
down_revision = '80444d37ab09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_contact',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('social_network', sa.String(), nullable=False),
    sa.Column('mentor_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('mentor', 'contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentor', sa.Column('contacts', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_table('mentor_contact')
    # ### end Alembic commands ###